# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

MyStruct <- new.env(parent = emptyenv())

MyStruct$new <- function() .Call(wrap__MyStruct__new)

MyStruct$restore_from_robj <- function(robj) .Call(wrap__MyStruct__restore_from_robj, robj)

#' @export
`$.MyStruct` <- function (self, name) { func <- MyStruct[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MyStruct` <- `$.MyStruct`

SomethingElse <- new.env(parent = emptyenv())

SomethingElse$new <- function() .Call(wrap__SomethingElse__new)

SomethingElse$try_restore_from_robj <- function(robj) .Call(wrap__SomethingElse__try_restore_from_robj, robj)

#' @export
`$.SomethingElse` <- function (self, name) { func <- SomethingElse[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SomethingElse` <- `$.SomethingElse`

